/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-sd:src/main/java/project/domain/Entity.e.vm.java
 */
package com.sera.model;


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

@Entity
@Table(name = "sera_cenv_giris")
public class SeraCenvGiris  {
    
    // Raw attributes
    private String tarih;
    private double deger;
    private Date creationDate;
    private Long createdBy;
    private Long baslikId;
    private Long id; // pk
    private Long ilkDeger;

    // ---------------------------
    // Constructors
    // ---------------------------

    public SeraCenvGiris() {
    }

    public SeraCenvGiris(Long primaryKey) {
        setId(primaryKey);
    }


    // -- [tarih] ------------------------
 
    @Column(name = "TARIH", length = 10)
    public String getTarih() {
        return tarih;
    }

    public void setTarih(String tarih) {
        this.tarih = tarih;
    }


    // -- [deger] ------------------------

    @Column(name = "DEGER", precision = 19)
    public double getDeger() {
        return deger;
    }

    @Column(name = "CREATED_BY", length = 10)
    public Long getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	public void setDeger(double deger) {
        this.deger = deger;
    }

    // -- [creationDate] ------------------------

    @Column(name = "CREATION_DATE", length = 10)
    public Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }


    // -- [baslikId] ------------------------

    @Column(name = "BASLIK_ID", precision = 19)
    public Long getBaslikId() {
        return baslikId;
    }

    public void setBaslikId(Long baslikId) {
        this.baslikId = baslikId;
    }

    // -- [id] ------------------------

    @NotNull
    @Column(name = "ID", precision = 19)
    @GeneratedValue
    @Id
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }


    // -- [ilkDeger] ------------------------

    @Column(name = "ILK_DEGER", precision = 19)
    public Long getIlkDeger() {
        return ilkDeger;
    }

    public void setIlkDeger(Long ilkDeger) {
        this.ilkDeger = ilkDeger;
    }

   
}