/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-sd:src/main/java/project/domain/Entity.e.vm.java
 */
package com.sera.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Size;
import org.apache.log4j.Logger;

@Entity
@Table(name = "sera_cenv_sabitler")
public class SeraCenvSabitler {
        // Raw attributes
    private String baslik;
    private Long sabit;
    private Long deger;
    private String aciklama;
    private Long parentId;
    private Long sabitler;
    private Long id; // pk

   
    // -- [baslik] ------------------------

    @Size(max = 64)
    @Column(name = "BASLIK", length = 64)
    public String getBaslik() {
        return baslik;
    }

    public void setBaslik(String baslik) {
        this.baslik = baslik;
    }

    // -- [sabit] ------------------------

    @Column(name = "SABIT", precision = 19)
    public Long getSabit() {
        return sabit;
    }

    public void setSabit(Long sabit) {
        this.sabit = sabit;
    }

    // -- [deger] ------------------------

    @Column(name = "DEGER", precision = 19)
    public Long getDeger() {
        return deger;
    }

    public void setDeger(Long deger) {
        this.deger = deger;
    }

    // -- [aciklama] ------------------------

    @Size(max = 256)
    @Column(name = "ACIKLAMA", length = 256)
    public String getAciklama() {
        return aciklama;
    }

    public void setAciklama(String aciklama) {
        this.aciklama = aciklama;
    }

    // -- [parentId] ------------------------

    @Column(name = "PARENT_ID", precision = 19)
    public Long getParentId() {
        return parentId;
    }

    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    // -- [sabitler] ------------------------

    @Column(name = "SABITLER", precision = 19)
    public Long getSabitler() {
        return sabitler;
    }

    public void setSabitler(Long sabitler) {
        this.sabitler = sabitler;
    }

    // -- [id] ------------------------

    @Column(name = "ID", precision = 19)
    @GeneratedValue
    @Id
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

   
}