/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-sd:src/main/java/project/domain/Entity.e.vm.java
 */
package com.sera.model;


import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import com.sera.util.ElemanTip;

@Entity
@Table(name = "sera_cenv_deger_liste")
public class SeraCenvDegerListe {
    
    // Raw attributes
    private Long id; // pk
    private String baslik; // not null
    private Long parentId; // not null
    private String tip1; // not null
    private String tip2; // not null
    private Long seviye; // not null
    private String birim; // not null
    private  List<String> agacElemanlar;

    // ---------------------------
    // Constructors
    // ---------------------------

    public List<String> getagacElemanlar() {
		return agacElemanlar;
	}

	public void setagacElemanlar(List<String> agacElemanlar) {
		this.agacElemanlar = ElemanTip.getInstance().agacElemanlar;
	}

	public SeraCenvDegerListe() {
    }

    public SeraCenvDegerListe(Long primaryKey) {
        setId(primaryKey);
    }

   
    // -------------------------------
    // Getter & Setter
    // -------------------------------

    // -- [id] ------------------------

    @Column(name = "ID", precision = 20)
    @GeneratedValue
    @Id
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    // -- [baslik] ------------------------


    @Column(name = "BASLIK", nullable = false, length = 64)
    public String getBaslik() {
        return baslik;
    }

    public void setBaslik(String baslik) {
        this.baslik = baslik;
    }

    // -- [parentId] ------------------------

    @Column(name = "PARENT_ID", nullable = false, precision = 20)
    public Long getParentId() {
        return parentId;
    }

    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    // -- [tip1] ------------------------

    @Column(name = "tip1", nullable = false, length = 8)
    public String gettip1() {
        return tip1;
    }

    public void settip1(String tip1) {
        this.tip1 = tip1;
    }

    // -- [tip2] ------------------------

    @Column(name = "TIP2", nullable = false, length = 8)
    public String getTip2() {
        return tip2;
    }

    public void setTip2(String tip2) {
        this.tip2 = tip2;
    }

    // -- [seviye] ------------------------

    @Column(name = "SEVIYE", nullable = false, precision = 20)
    public Long getSeviye() {
        return seviye;
    }

    public void setSeviye(Long seviye) {
        this.seviye = seviye;
    }

    // -- [birim] ------------------------

    @Column(name = "BIRIM", nullable = false, length = 15)
    public String getBirim() {
        return birim;
    }

    public void setBirim(String birim) {
        this.birim = birim;
    }

   


  
}