/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend-sd:src/main/java/project/domain/Entity.e.vm.java
 */
package com.sera.model;


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "sera_cenv_donem_sonuc")
public class SeraCenvDonemSonuc  {
   
    // Raw attributes
    private String donem;
    private String baslik;
    private String deger;
    private Date baslangicTarihi;
    private Date bitisTarihi;
    private Long baslikId;
    private Long sonuc;
    private Long ilkSonuc;
    private Long co2;
    private Long ch4;
    private Long n2o;
    private Long tco2e;
    private Long id; // pk

   
    @Column(name = "DONEM", length = 16)
    public String getDonem() {
        return donem;
    }

    public void setDonem(String donem) {
        this.donem = donem;
    }

    @Column(name = "BASLIK", length = 64)
    public String getBaslik() {
        return baslik;
    }

    public void setBaslik(String baslik) {
        this.baslik = baslik;
    }

    
    @Column(name = "DEGER", length = 100)
    public String getDeger() {
        return deger;
    }

    public void setDeger(String deger) {
        this.deger = deger;
    }

    // -- [baslangicTarihi] ------------------------

    @Column(name = "BASLANGIC_TARIHI", length = 10)
    public Date getBaslangicTarihi() {
        return baslangicTarihi;
    }

    public void setBaslangicTarihi(Date baslangicTarihi) {
        this.baslangicTarihi = baslangicTarihi;
    }

    // -- [bitisTarihi] ------------------------

    @Column(name = "BITIS_TARIHI", length = 10)
    public Date getBitisTarihi() {
        return bitisTarihi;
    }

    public void setBitisTarihi(Date bitisTarihi) {
        this.bitisTarihi = bitisTarihi;
    }

    // -- [baslikId] ------------------------

    @Column(name = "BASLIK_ID", precision = 19)
    public Long getBaslikId() {
        return baslikId;
    }

    public void setBaslikId(Long baslikId) {
        this.baslikId = baslikId;
    }

    // -- [sonuc] ------------------------

    @Column(name = "SONUC", precision = 19)
    public Long getSonuc() {
        return sonuc;
    }

    public void setSonuc(Long sonuc) {
        this.sonuc = sonuc;
    }

    // -- [ilkSonuc] ------------------------

    @Column(name = "ILK_SONUC", precision = 19)
    public Long getIlkSonuc() {
        return ilkSonuc;
    }

    public void setIlkSonuc(Long ilkSonuc) {
        this.ilkSonuc = ilkSonuc;
    }

    // -- [co2] ------------------------

    @Column(name = "CO2", precision = 19)
    public Long getCo2() {
        return co2;
    }

    public void setCo2(Long co2) {
        this.co2 = co2;
    }

    // -- [ch4] ------------------------

    @Column(name = "CH4", precision = 19)
    public Long getCh4() {
        return ch4;
    }

    public void setCh4(Long ch4) {
        this.ch4 = ch4;
    }

    // -- [n2o] ------------------------

    @Column(name = "N2O", precision = 19)
    public Long getN2o() {
        return n2o;
    }

    public void setN2o(Long n2o) {
        this.n2o = n2o;
    }

    // -- [tco2e] ------------------------

    @Column(name = "TCO2E", precision = 19)
    public Long getTco2e() {
        return tco2e;
    }

    public void setTco2e(Long tco2e) {
        this.tco2e = tco2e;
    }

    // -- [id] ------------------------

    @Column(name = "ID", precision = 19)
    @GeneratedValue
    @Id
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
   

}